#!/usr/bin/env bash
# Start Playwright container for screenshot capture and testing
# Automatically configures all required environment variables
# Detects if rebuild is needed and rebuilds/restarts automatically

set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/../.." && pwd)"

# Colors for output
BLUE='\033[0;34m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
RED='\033[0;31m'
NC='\033[0m'

echo -e "${BLUE}Starting Playwright Container${NC}"
echo ""

# Build tracking file
BUILD_HASH_FILE="${SCRIPT_DIR}/.build-hash"

# Source workspace environment
if [[ -f "${PROJECT_ROOT}/.env.workspace" ]]; then
    # shellcheck source=/dev/null
    source "${PROJECT_ROOT}/.env.workspace"
else
    echo -e "${RED}ERROR: .env.workspace not found${NC}" >&2
    echo "Run .devcontainer/post-create.sh first" >&2
    exit 1
fi

# Required variables from .env.workspace
: "${DOCKER_UID:?DOCKER_UID must be set (source .env.workspace)}"
: "${DOCKER_GID:?DOCKER_GID must be set (source .env.workspace)}"
: "${DOCKER_NETWORK_INTERNAL:?DOCKER_NETWORK_INTERNAL must be set (source .env.workspace)}"
: "${PHYSICAL_REPO_ROOT:?PHYSICAL_REPO_ROOT must be set (source .env.workspace)}"

# PHYSICAL_PLAYWRIGHT_DIR: Where to store container volume data on host
# Points directly to deploy-local which contains screenshots directory
PHYSICAL_PLAYWRIGHT_DIR="${PHYSICAL_PLAYWRIGHT_DIR:-${PHYSICAL_REPO_ROOT}/deploy-local}"

echo "Screenshot directory: ${PHYSICAL_PLAYWRIGHT_DIR}/screenshots"

# Create .env file for docker-compose
ENV_FILE="${SCRIPT_DIR}/.env"
cat > "${ENV_FILE}" <<EOF
# Playwright Container Environment
# Auto-generated by start-playwright.sh

# Docker settings
DOCKER_UID=${DOCKER_UID}
DOCKER_GID=${DOCKER_GID}
DOCKER_NETWORK_INTERNAL=${DOCKER_NETWORK_INTERNAL}

# Volume mounts (physical host paths)
PHYSICAL_REPO_ROOT=${PHYSICAL_REPO_ROOT}
PHYSICAL_PLAYWRIGHT_DIR=${PHYSICAL_PLAYWRIGHT_DIR}

# Playwright settings
PLAYWRIGHT_HEADLESS=${PLAYWRIGHT_HEADLESS:-true}
PLAYWRIGHT_BROWSER=${PLAYWRIGHT_BROWSER:-chromium}

# MCP settings (disabled by default for screenshot use)
MCP_ENABLED=${MCP_ENABLED:-false}
MCP_PORT=${MCP_PORT:-8765}
MCP_SERVER_NAME=${MCP_SERVER_NAME:-playwright-mcp}
EOF

echo -e "${GREEN}✓ Environment configured${NC}"
echo ""

# Calculate hash of build inputs to detect changes
calculate_build_hash() {
    # Hash Dockerfile, requirements.root.txt, and mcp_server.py
    # Use md5sum (cross-platform compatible in Docker environments)
    {
        cat "${SCRIPT_DIR}/Dockerfile"
        cat "${SCRIPT_DIR}/requirements.root.txt"
        cat "${SCRIPT_DIR}/mcp_server.py"
    } | md5sum | cut -d' ' -f1
}

# Check if rebuild is needed
needs_rebuild() {
    local current_hash
    current_hash=$(calculate_build_hash)
    
    # Check if image exists
    if ! docker image inspect generic-playwright:latest &>/dev/null; then
        echo -e "${YELLOW}Image 'generic-playwright:latest' not found - build required${NC}"
        echo "${current_hash}" > "${BUILD_HASH_FILE}"
        return 0  # true, needs rebuild
    fi
    
    # Check if hash file exists
    if [[ ! -f "${BUILD_HASH_FILE}" ]]; then
        echo -e "${YELLOW}No build hash found - rebuild recommended${NC}"
        echo "${current_hash}" > "${BUILD_HASH_FILE}"
        return 0  # true, needs rebuild
    fi
    
    # Compare hashes
    local stored_hash
    stored_hash=$(cat "${BUILD_HASH_FILE}")
    
    if [[ "${current_hash}" != "${stored_hash}" ]]; then
        echo -e "${YELLOW}Build inputs changed - rebuild required${NC}"
        echo "  Previous: ${stored_hash}"
        echo "  Current:  ${current_hash}"
        echo "${current_hash}" > "${BUILD_HASH_FILE}"
        return 0  # true, needs rebuild
    fi
    
    return 1  # false, no rebuild needed
}

# Rebuild container if needed
cd "${SCRIPT_DIR}"

if needs_rebuild; then
    echo -e "${BLUE}Building Playwright container...${NC}"
    echo ""
    
    # Stop and remove existing container if running
    if docker ps -a --format '{{.Names}}' | grep -q '^playwright$'; then
        echo -e "${YELLOW}Stopping existing container...${NC}"
        docker stop playwright 2>/dev/null || true
        docker rm playwright 2>/dev/null || true
    fi
    
    # Build using docker compose (respects build context properly)
    if docker compose build --progress=plain; then
        echo ""
        echo -e "${GREEN}✓ Container built successfully${NC}"
        echo ""
    else
        echo ""
        echo -e "${RED}ERROR: Container build failed${NC}" >&2
        exit 1
    fi
else
    echo -e "${GREEN}✓ Container image up-to-date (no rebuild needed)${NC}"
    echo ""
fi

# Check if container is already running
if docker ps --format '{{.Names}}' | grep -q '^playwright$'; then
    echo -e "${YELLOW}Container already running - restarting to apply configuration...${NC}"
    docker compose restart
else
    # Start container
    docker compose up -d
fi

echo ""
echo -e "${GREEN}✓ Playwright container started${NC}"
echo ""
echo "Usage:"
echo "  • Run screenshots: ${SCRIPT_DIR}/playwright-exec.sh python3 /workspace/ui_tests/capture_ui_screenshots.py"
echo "  • Run tests:       ${SCRIPT_DIR}/playwright-exec.sh pytest /workspace/ui_tests/tests -v"
echo "  • Stop container:  docker stop playwright"
echo ""
echo "Rebuild info:"
echo "  • Build hash: $(cat "${BUILD_HASH_FILE}")"
echo "  • Force rebuild: rm ${BUILD_HASH_FILE} && ${SCRIPT_DIR}/start-playwright.sh"
echo ""
